<?php
// Nav Menu Items
$navItemsNL = array(	
	array('slug' 	=> 'shemale-drenthe','title' 	=> 'Drenthe'),	
	array('slug' 	=> 'shemale-flevoland','title' 	=> 'Flevoland'),	
	array('slug' 	=> 'shemale-friesland','title' 	=> 'Friesland'),	
	array('slug' 	=> 'shemale-gelderland','title' => 'Gelderland'),	
	array('slug' 	=> 'shemale-groningen','title' 	=> 'Groningen'),	
	array('slug' 	=> 'shemale-limburg-nl','title' 	=> 'Limburg'	),	
	array('slug' 	=> 'shemale-noord-brabant','title' => 'Noord-Brabant'	),	
	array('slug' 	=> 'shemale-noord-holland','title' => 'Noord-Holland'	),	
	array('slug' 	=> 'shemale-overijssel','title' => 'Overijssel'	),	
	array('slug' 	=> 'shemale-utrecht','title' 	=> 'Utrecht'	),	
	array('slug' 	=> 'shemale-zeeland','title' 	=> 'Zeeland'	),	
	array('slug' 	=> 'shemale-zuid-holland','title' => 'Zuid-Holland'),
);
$navItemsBE = array(
	array('slug' 	=> 'shemale-antwerpen','title' => 'Antwerpen'	),	
	array('slug' 	=> 'shemale-brussel','title' 	=> 'Brussel'	),	
	array('slug' 	=> 'shemale-henegouwen','title'=> 'Henegouwen'	),	
	array('slug' 	=> 'shemale-limburg-be','title' 	=> 'Limburg'	),	
	array('slug' 	=> 'shemale-luik','title' 	=> 'Luik'	),	
	array('slug' 	=> 'shemale-luxemburg','title'	=> 'Luxemburg'	),	
	array('slug' 	=> 'shemale-namen','title' 	=> 'Namen'	),
	array('slug' 	=> 'shemale-oost-vlaanderen','title' => 'Oost-Vlaanderen'),	
	array('slug' 	=> 'shemale-vlaams-brabant','title' => 'Vlaams-Brabant'),	
	array('slug' 	=> 'shemale-waals-brabant','title' => 'Waals-Brabant'	),	
	array('slug' 	=> 'shemale-west-vlaanderen','title' => 'West-Vlaanderen'),
);
$navItemsUK = array(       
	array('slug' => 'shemale-east-midlands','title' => 'East Midlands'),        
	array('slug' => 'shemale-east-of-england','title' => 'East of England'),        
	array('slug' => 'shemale-london','title' => 'London'),        
	array('slug' => 'shemale-north-east-england','title' => 'North East England'),        
	array('slug' => 'shemale-north-west-england','title' => 'North West England'),        
	array('slug' => 'shemale-northern-ireland','title' => 'Northern Ireland'),        
	array('slug' => 'shemale-scotland','title' => 'Scotland'),        
	array('slug' => 'shemale-south-east-england','title' => 'South East England'),        
	array('slug' => 'shemale-south-west-england','title' => 'South West England'),        
	array('slug' => 'shemale-wales','title' => 'Wales'),        
	array('slug' => 'shemale-west-midlands','title' => 'West Midlands'),        
	array('slug' => 'shemale-yorkshire-and-the-humber','title' => 'Yorkshire and The Humber'),
);
$navItemsDE = array(        
	array('slug' => 'shemale-baden-wurttemberg','title' => 'Baden-Wurttemberg'),        
	array('slug' => 'shemale-bayern','title' => 'Bayern'),        
	array('slug' => 'shemale-berlin','title' => 'Berlin'),        
	array('slug' => 'shemale-brandenburg','title' => 'Brandenburg'),        
	array('slug' => 'shemale-bremen','title' => 'Bremen'),        
	array('slug' => 'shemale-hamburg','title' => 'Hamburg'),        
	array('slug' => 'shemale-hessen','title' => 'Hessen'),        
	array('slug' => 'shemale-mecklenburg-vorpommern','title' => 'Mecklenburg-Vorpommern'),        
	array('slug' => 'shemale-niedersachsen','title' => 'Niedersachsen'),        
	array('slug' => 'shemale-nordrhein-westfalen','title' => 'Nordrhein-Westfalen'),        
	array('slug' => 'shemale-rheinland-pfalz','title' => 'Rheinland-Pfalz'),        
	array('slug' => 'shemale-saarland','title' => 'Saarland'),        
	array('slug' => 'shemale-sachsen','title' => 'Sachsen'),        
	array('slug' => 'shemale-sachsen-anhalt','title' => 'Sachsen-Anhalt'),        
	array('slug' => 'shemale-schleswig-holstein','title' => 'Schleswig-Holstein'),        
	array('slug' => 'shemale-thuringen','title' => 'Thuringen'),
);
$navItemsAT = array(       
	array('slug' => 'shemale-burgenland','title' => 'Burgenland'),        
	array('slug' => 'shemale-karnten','title' => 'Kärnten'),        
	array('slug' => 'shemale-niederosterreich','title' => 'Niederösterreich'),        
	array('slug' => 'shemale-oberosterreich','title' => 'Oberösterreich'),        
	array('slug' => 'shemale-salzburg','title' => 'Salzburg'),        
	array('slug' => 'shemale-steiermark','title' => 'Steiermark'),        
	array('slug' => 'shemale-tirol','title' => 'Tirol'),        
	array('slug' => 'shemale-vorarlberg','title' => 'Vorarlberg'),        
	array('slug' => 'shemale-wien','title' => 'Wien'),
);
$navItemsCH = array(        
	array('slug' => 'shemale-aargau','title' => 'Aargau'),        
	array('slug' => 'shemale-appenzell','title' => 'Appenzell'),        
	array('slug' => 'shemale-basel-land','title' => 'Basel-Land'),        
	array('slug' => 'shemale-basel-stadt','title' => 'Basel-Stadt'),        
	array('slug' => 'shemale-bern','title' => 'Bern'),        
	array('slug' => 'shemale-fribourg','title' => 'Fribourg'),        
	array('slug' => 'shemale-geneve','title' => 'Genève'),        
	array('slug' => 'shemale-glarus','title' => 'Glarus'),        
	array('slug' => 'shemale-graubunden','title' => 'Graubünden'),        
	array('slug' => 'shemale-jura','title' => 'Jura'),        
	array('slug' => 'shemale-luzern','title' => 'Luzern'),        
	array('slug' => 'shemale-neuchatel','title' => 'Neuchâtel'),        
	array('slug' => 'shemale-nidwalden','title' => 'Nidwalden'),        
	array('slug' => 'shemale-obwalden','title' => 'Obwalden'),        
	array('slug' => 'shemale-schaffhausen','title' => 'Schaffhausen'),        
	array('slug' => 'shemale-schwyz','title' => 'Schwyz'),        
	array('slug' => 'shemale-solothurn','title' => 'Solothurn'),        
	array('slug' => 'shemale-st-gallen','title' => 'St. Gallen'),        
	array('slug' => 'shemale-thurgau','title' => 'Thurgau'),        
	array('slug' => 'shemale-ticino','title' => 'Ticino'),       
	array('slug' => 'shemale-uri','title' => 'Uri'),        
	array('slug' => 'shemale-valais','title' => 'Valais'),        
	array('slug' => 'shemale-vaud','title' => 'Vaud'),        
	array('slug' => 'shemale-zug','title' => 'Zug'),
	array('slug' => 'shemale-zurich','title' => 'Zürich'),
);

$navItemsTips = array(
        array('slug' => 'datingtips','title' => 'Datingtips'),
        array('slug' => 'datingtips-nederland','title' => 'Datingtips Nederland'),
        array('slug' => 'datingtips-belgie','title' => 'Datingtips België'),
        array('slug' => 'datingtips-duitsland','title' => 'Datingtips Duitsland'),
        array('slug' => 'datingtips-verenigd-koninkrijk','title' => 'Datingtips Verenigd Koninkrijk'),
        array('slug' => 'datingtips-oostenrijk','title' => 'Datingtips Oostenrijk'),
        array('slug' => 'datingtips-zwitserland','title' => 'Datingtips Zwitserland'),
);
?>
