<?php
$partnerLinks = array(
    array('url' => 'https://18date.net/', 'label' => '18date.net'),
    array('url' => 'https://oproepjesnederland.nl/', 'label' => 'Oproepjes Nederland'),
    array('url' => 'https://zoekertjesbelgie.be', 'label' => 'Zoekertjes België'),
    array('url' => 'https://flirthonk.nl', 'label' => 'Flirthonk.nl | De grootste dating website van Nederland en België'),
    array('url' => 'http://www.adulttop50.nl', 'label' => 'Adult Top 50'),
    array('url' => 'http://www.topadultsites.nl', 'label' => 'Top Adultsites.nl'),
    array('url' => 'http://www.sextoplijst.com', 'label' => 'SexToplijst.com'),
    array('url' => 'http://www.xxxtop100.nl', 'label' => "Linda's XXX Top 100"),
    array('url' => 'https://www.sexstartnet.nl', 'label' => 'Sexstartnet Sexcontacten'),
    array('url' => 'https://sexdating.opzijnbest.nl', 'label' => 'sexdating opzijnbest'),
    array('url' => 'https://sexdate.sitelinkje.nl', 'label' => 'sexdate sitelinkje'),
    array('url' => 'http://relatie.vindhetviahier.nl', 'label' => 'Relatie startpagina'),
    array('url' => 'http://sexdate.startplezier.nl/', 'label' => 'startplezier sexdate'),
    array('url' => 'http://www.linkorado.com/', 'label' => 'Linkorado'),
    array('url' => 'http://sexdate.start.be/', 'label' => 'sexdate'),
    array('url' => 'http://gratissex.start.be/', 'label' => 'gratissex'),
    array('url' => 'http://sexchat.start.be/', 'label' => 'sexchat start'),
    array('url' => 'http://sexdate.favos.nl/', 'label' => 'sexdate'),
    array('url' => 'http://sexdating.favos.nl/', 'label' => 'sexdating'),
    array('url' => 'http://sexdaten.favos.nl/', 'label' => "sexdaten favo's"),
    array('url' => 'http://sexdate.b9.nl/', 'label' => 'sexdate'),
    array('url' => 'http://sekstips.b9.nl/', 'label' => 'sekstips'),
    array('url' => 'http://datingtips.b9.nl/', 'label' => 'datingtips b9'),
    array('url' => 'http://sexdate.tipjes.nl/', 'label' => 'sexdate'),
    array('url' => 'http://sexdating.tipjes.nl/', 'label' => 'sexdating'),
    array('url' => 'http://gratissex.tipjes.nl/', 'label' => 'gratissex tipjes'),
    array('url' => 'http://sexdate.linkspot.nl/', 'label' => 'sexdate'),
    array('url' => 'http://sekstips.linkspot.nl/', 'label' => 'sekstips'),
    array('url' => 'http://seks.linkspot.nl/', 'label' => 'seks linkspot'),
    array('url' => 'http://sexdate.startpagina.net/', 'label' => 'sexdate'),
    array('url' => 'http://sexdating.startpagina.net/', 'label' => 'sexdating'),
    array('url' => 'http://gratissex.startpagina.net/', 'label' => 'gratissex startpagina'),
    array('url' => 'http://gratis-sexdating.links.nl', 'label' => 'gratis-sexdating'),
    array('url' => 'http://sexdate.links.nl', 'label' => 'sexdate'),
    array('url' => 'http://sexdaten.links.nl', 'label' => 'sexdaten links'),
    array('url' => 'http://sexdate.webgidsje.nl', 'label' => 'sexdate'),
    array('url' => 'http://sexdating.webgidsje.nl', 'label' => 'sexdating'),
    array('url' => 'http://sexchat.webgidsje.nl', 'label' => 'sexchat webgidsje'),
    array('url' => 'http://sexdate.zoekvinden.nl/', 'label' => 'zoek sexdate'),
    array('url' => 'http://sexdating.zoekvinden.nl/', 'label' => 'sexdating'),
    array('url' => 'http://gratisseks.zoekvinden.nl/', 'label' => 'gratisseks vinden'),
    array('url' => 'http://sexdate.linkjespagina.nl/', 'label' => 'sexdate'),
    array('url' => 'http://seks.linkjespagina.nl/', 'label' => 'seks'),
    array('url' => 'http://sekstips.linkjespagina.nl/', 'label' => 'sekstips linkjespagina'),
    array('url' => 'http://sexdate.linkgoed.nl/', 'label' => 'sexdate'),
    array('url' => 'http://sexdates.linkgoed.nl/', 'label' => 'sexdates'),
    array('url' => 'http://gratissex.linkgoed.nl/', 'label' => 'gratissex linkgoed'),
    array('url' => 'http://sexdate.eigenstart.nl/', 'label' => 'eigen sexdate'),
    array('url' => 'http://sexdating.eigenstart.nl/', 'label' => 'sexdating start'),
    array('url' => 'http://sexdate.startbewijs.nl/', 'label' => 'start sexdate'),
    array('url' => 'http://sexdating.startbewijs.nl/', 'label' => 'sexdating bewijs'),
    array('url' => 'http://sexdate.m4n.nl/', 'label' => 'sexdate'),
    array('url' => 'http://sexdating.m4n.nl/', 'label' => 'sexdating m4n'),
    array('url' => 'http://gratis-datingsites.jouwpagina.nl', 'label' => 'jouw gratis-datingsites'),
    array('url' => 'http://sexdate.jouwpagina.nl', 'label' => 'sexdate pagina'),
    array('url' => 'http://gratissex.boogolinks.nl', 'label' => 'boogo gratissex'),
    array('url' => 'http://sexdate.boogolinks.nl', 'label' => 'sexdate links'),
    array('url' => 'http://sexdating.bestelinks.nl', 'label' => 'beste sexdating'),
    array('url' => 'http://sexdate.bestelinks.nl', 'label' => 'sexdate links'),
    array('url' => 'http://sexdate.eigenoverzicht.nl/', 'label' => 'eigen sexdate'),
    array('url' => 'http://sexdating.eigenoverzicht.nl/', 'label' => 'sexdating overzicht'),
    array('url' => 'http://sexdatingnederland.jouwpagina.be', 'label' => 'sexdatingnederland'),
    array('url' => 'http://sexdatingbelgie.jouwpagina.be', 'label' => 'sexdatingbelgie'),
    array('url' => 'http://sexdate.jouwbegin.nl', 'label' => 'sexdate'),
    array('url' => 'http://sexdating.jouwbegin.nl', 'label' => 'sexdating')
);
?>
